#!/usr/bin/env python3
"""Generate the figures for ``bohr_mollerup_convex.md``.

The note shows that convexity (as opposed to log-convexity) does *not* single out
the Gamma function: for small ``eps`` the function

    f_eps(x) = Gamma(x) * (1 + eps * (1 - cos(2*pi*x)))

is a positive, convex solution of ``f(x+1) = x f(x)`` with ``f(1) = 1`` that is
different from ``Gamma`` and is not log-convex.

This script produces two PNGs under ``figures/`` (git-ignored; regenerated by the
``plots`` pixi task, on which ``build``/``start`` depend):

* ``bohr_mollerup_convex_scalings.png`` -- Gamma vs f_eps in four scalings; the
  ripple is invisible on the linear axis but shows up on the log axes.
* ``bohr_mollerup_convex_derivs.png`` -- values vs derivatives. In ``f'`` the
  convex counterexample stays monotone (convex); only in the log-derivative
  ``(log f)' = f'/f`` does its wiggle surface (non-monotone => not log-convex).
"""

from __future__ import annotations

import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import gamma

OUT = Path(__file__).resolve().parent / "figures"

EPS_SMALL = 0.01  # convex counterexample
EPS_BIG = 0.20    # larger, non-convex; only used to make the oscillation obvious


def g(eps: float, x: np.ndarray) -> np.ndarray:
    return 1 + eps * (1 - np.cos(2 * np.pi * x))


def f(eps: float, x: np.ndarray) -> np.ndarray:
    return gamma(x) * g(eps, x)


def plot_scalings(x: np.ndarray) -> None:
    """Gamma and f_eps in the four requested scalings."""
    G, Fs, Fb = gamma(x), f(EPS_SMALL, x), f(EPS_BIG, x)
    fig, ax = plt.subplots(2, 2, figsize=(13, 9), layout="constrained")

    def draw(a, title):
        a.plot(x, G, "k", lw=2.0, label=r"$\Gamma(x)$")
        a.plot(x, Fs, "tab:blue", lw=1.3, label=r"$f_{0.01}$ (convex)")
        a.plot(x, Fb, "tab:red", lw=1.3, label=r"$f_{0.20}$ (non-convex)")
        a.set_title(title)
        a.set_xlabel("x")
        a.grid(alpha=0.3)
        a.legend(fontsize=8)

    draw(ax[0, 0], "linear"); ax[0, 0].set_ylabel("f(x)")
    draw(ax[0, 1], "semilogx"); ax[0, 1].set_xscale("log")
    draw(ax[1, 0], "semilogy"); ax[1, 0].set_yscale("log"); ax[1, 0].set_ylabel("f(x)")
    draw(ax[1, 1], "log-log"); ax[1, 1].set_xscale("log"); ax[1, 1].set_yscale("log")
    fig.suptitle(
        r"$\Gamma$ vs $f_\varepsilon(x)=\Gamma(x)\,(1+\varepsilon(1-\cos 2\pi x))$"
        r"  —  the ripple hides on the linear axis, shows on the log axes",
        fontsize=13,
    )
    fig.savefig(OUT / "bohr_mollerup_convex_scalings.png", dpi=130)
    plt.close(fig)


def plot_derivs(x: np.ndarray) -> None:
    """Values vs derivatives; the convex ripple only surfaces in (log f)'."""
    Fs, Fb = f(EPS_SMALL, x), f(EPS_BIG, x)
    d = lambda a: np.gradient(a, x)              # noqa: E731  f'
    dlog = lambda a: np.gradient(np.log(a), x)   # noqa: E731  (log f)' = f'/f

    fig, ax = plt.subplots(2, 2, figsize=(13.5, 9), layout="constrained")

    ax[0, 0].plot(x, Fs, "tab:blue", lw=1.4, label=r"$f_{0.01}$ (convex)")
    ax[0, 0].plot(x, Fb, "tab:red", lw=1.4, label=r"$f_{0.20}$")
    ax[0, 0].set_title("linear — values"); ax[0, 0].set_ylabel("f(x)")
    ax[0, 0].grid(alpha=0.3); ax[0, 0].legend(fontsize=8)

    ax[0, 1].plot(x, d(Fs), "tab:blue", lw=1.4)
    ax[0, 1].plot(x, d(Fb), "tab:red", lw=1.4)
    ax[0, 1].set_title(r"linear — derivative $f'(x)$   (red dips $\Rightarrow$ not convex)")
    ax[0, 1].grid(alpha=0.3)

    ax[1, 0].plot(x, Fs, "tab:blue", lw=1.4)
    ax[1, 0].plot(x, Fb, "tab:red", lw=1.4)
    ax[1, 0].set_yscale("log"); ax[1, 0].set_title("semilogy — values")
    ax[1, 0].set_xlabel("x"); ax[1, 0].set_ylabel("f(x)"); ax[1, 0].grid(alpha=0.3)

    a = ax[1, 1]
    a.plot(x, dlog(Fs), "tab:blue", lw=1.4, label=r"$(\log f_{0.01})'$")
    a.plot(x, dlog(Fb), "tab:red", lw=1.4, label=r"$(\log f_{0.20})'$")
    a.set_title(r"semilogy — log-derivative $(\log f)'=f'/f$")
    a.set_xlabel("x"); a.grid(alpha=0.3); a.legend(fontsize=8, loc="upper left")
    axins = a.inset_axes([0.55, 0.09, 0.42, 0.40])
    axins.plot(x, dlog(Fs), "tab:blue", lw=1.6)
    axins.set_xlim(3.5, 6); axins.set_ylim(0.95, 1.8); axins.grid(alpha=0.3)
    axins.set_title(r"zoom: $(\log f_{0.01})'$ wiggles", fontsize=8)
    a.indicate_inset_zoom(axins, edgecolor="gray")

    fig.suptitle(
        r"convex $f_{0.01}$ (blue) and $f_{0.20}$ (red): "
        r"values (left) vs derivatives (right)",
        fontsize=13,
    )
    fig.savefig(OUT / "bohr_mollerup_convex_derivs.png", dpi=130)
    plt.close(fig)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    x = np.linspace(0.25, 6.0, 16000)
    plot_scalings(x)
    plot_derivs(x)
    print(f"Wrote figures to {OUT}")


if __name__ == "__main__":
    main()
